# Site settings
name: Harsh Raj
title: Harsh Raj | Software Engineer
description: Highly motivated software engineer, focused on building applications that exceeds user's expectations
url: https://harshraj32.github.io/
baseurl: ''
email: harshraj201999@gmail.com
cover: https://harshraj32.github.io/img/og.png
logo: https://harshraj32.github.io/img/emojis/technologist.png
resume: https://harshraj32.github.io/resume.pdf
social:
  - title: email
    url: mailto:harshraj201999@gmail.com
  - title: twitter
    url: https://twitter.com/harshraj32
  - title: instagram
    url: https://instagram.com/jharshraj
  - title: github
    url: https://github.com/harshraj32
  

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
